spring:
     datasource:
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://localhost:3306/foro_alura
         username: root
         password: Sh1nr4-t3ns31
     jpa:
         show-sql: true
         hibernate:
             ddl-auto: update
         properties:
             hibernate:
               format_sql: true
server:
     port: 80
     error:
         include-stacktrace: never